#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-gfonts
Version  : 0.2.0
Release  : 1
URL      : https://cran.r-project.org/src/contrib/gfonts_0.2.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/gfonts_0.2.0.tar.gz
Summary  : Offline 'Google' Fonts for 'Markdown' and 'Shiny'
Group    : Development/Tools
License  : GPL-3.0
Requires: R-crayon
Requires: R-crul
Requires: R-glue
Requires: R-htmltools
Requires: R-jsonlite
Requires: R-shiny
BuildRequires : R-crayon
BuildRequires : R-crul
BuildRequires : R-glue
BuildRequires : R-htmltools
BuildRequires : R-jsonlite
BuildRequires : R-shiny
BuildRequires : R-vcr
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
'shiny' applications. Some popular fonts are included and ready to use.

%prep
%setup -q -n gfonts
cd %{_builddir}/gfonts

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1673901173

%install
export SOURCE_DATE_EPOCH=1673901173
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/gfonts/DESCRIPTION
/usr/lib64/R/library/gfonts/INDEX
/usr/lib64/R/library/gfonts/Meta/Rd.rds
/usr/lib64/R/library/gfonts/Meta/data.rds
/usr/lib64/R/library/gfonts/Meta/features.rds
/usr/lib64/R/library/gfonts/Meta/hsearch.rds
/usr/lib64/R/library/gfonts/Meta/links.rds
/usr/lib64/R/library/gfonts/Meta/nsInfo.rds
/usr/lib64/R/library/gfonts/Meta/package.rds
/usr/lib64/R/library/gfonts/Meta/vignette.rds
/usr/lib64/R/library/gfonts/NAMESPACE
/usr/lib64/R/library/gfonts/NEWS.md
/usr/lib64/R/library/gfonts/R/gfonts
/usr/lib64/R/library/gfonts/R/gfonts.rdb
/usr/lib64/R/library/gfonts/R/gfonts.rdx
/usr/lib64/R/library/gfonts/R/sysdata.rdb
/usr/lib64/R/library/gfonts/R/sysdata.rdx
/usr/lib64/R/library/gfonts/assets/css/alegreya.css
/usr/lib64/R/library/gfonts/assets/css/baloo.css
/usr/lib64/R/library/gfonts/assets/css/happy-monkey.css
/usr/lib64/R/library/gfonts/assets/css/henny-penny.css
/usr/lib64/R/library/gfonts/assets/css/lato.css
/usr/lib64/R/library/gfonts/assets/css/montserrat.css
/usr/lib64/R/library/gfonts/assets/css/nunito-sans.css
/usr/lib64/R/library/gfonts/assets/css/open-sans.css
/usr/lib64/R/library/gfonts/assets/css/oswald.css
/usr/lib64/R/library/gfonts/assets/css/poppins.css
/usr/lib64/R/library/gfonts/assets/css/roboto.css
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-700.eot
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-700.svg
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-700.ttf
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-700.woff
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-700.woff2
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-italic.eot
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-italic.svg
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-italic.ttf
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-italic.woff
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-italic.woff2
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-regular.eot
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-regular.svg
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-regular.ttf
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-regular.woff
/usr/lib64/R/library/gfonts/assets/fonts/alegreya/alegreya-v13-latin-regular.woff2
/usr/lib64/R/library/gfonts/assets/fonts/baloo/baloo-2-v1-latin-regular.eot
/usr/lib64/R/library/gfonts/assets/fonts/baloo/baloo-2-v1-latin-regular.svg
/usr/lib64/R/library/gfonts/assets/fonts/baloo/baloo-2-v1-latin-regular.ttf
/usr/lib64/R/library/gfonts/assets/fonts/baloo/baloo-2-v1-latin-regular.woff
/usr/lib64/R/library/gfonts/assets/fonts/baloo/baloo-2-v1-latin-regular.woff2
/usr/lib64/R/library/gfonts/assets/fonts/happy-monkey/happy-monkey-v8-latin-regular.eot
/usr/lib64/R/library/gfonts/assets/fonts/happy-monkey/happy-monkey-v8-latin-regular.svg
/usr/lib64/R/library/gfonts/assets/fonts/happy-monkey/happy-monkey-v8-latin-regular.ttf
/usr/lib64/R/library/gfonts/assets/fonts/happy-monkey/happy-monkey-v8-latin-regular.woff
/usr/lib64/R/library/gfonts/assets/fonts/happy-monkey/happy-monkey-v8-latin-regular.woff2
/usr/lib64/R/library/gfonts/assets/fonts/henny-penny/henny-penny-v7-latin-regular.eot
/usr/lib64/R/library/gfonts/assets/fonts/henny-penny/henny-penny-v7-latin-regular.svg
/usr/lib64/R/library/gfonts/assets/fonts/henny-penny/henny-penny-v7-latin-regular.ttf
/usr/lib64/R/library/gfonts/assets/fonts/henny-penny/henny-penny-v7-latin-regular.woff
/usr/lib64/R/library/gfonts/assets/fonts/henny-penny/henny-penny-v7-latin-regular.woff2
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-300italic.eot
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-300italic.svg
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-300italic.ttf
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-300italic.woff
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-300italic.woff2
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-700.eot
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-700.svg
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-700.ttf
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-700.woff
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-700.woff2
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-regular.eot
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-regular.svg
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-regular.ttf
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-regular.woff
/usr/lib64/R/library/gfonts/assets/fonts/lato/lato-v16-latin-regular.woff2
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-300italic.eot
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-300italic.svg
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-300italic.ttf
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-300italic.woff
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-300italic.woff2
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-700.eot
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-700.svg
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-700.ttf
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-700.woff
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-700.woff2
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-regular.eot
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-regular.svg
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-regular.ttf
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-regular.woff
/usr/lib64/R/library/gfonts/assets/fonts/montserrat/montserrat-v14-latin-regular.woff2
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-700.eot
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-700.svg
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-700.ttf
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-700.woff
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-700.woff2
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-italic.eot
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-italic.svg
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-italic.ttf
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-italic.woff
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-italic.woff2
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-regular.eot
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-regular.svg
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-regular.ttf
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-regular.woff
/usr/lib64/R/library/gfonts/assets/fonts/nunito-sans/nunito-sans-v5-latin-regular.woff2
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-300italic.eot
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-300italic.svg
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-300italic.ttf
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-300italic.woff
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-300italic.woff2
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-700.eot
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-700.svg
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-700.ttf
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-700.woff
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-700.woff2
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-regular.eot
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-regular.svg
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-regular.ttf
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-regular.woff
/usr/lib64/R/library/gfonts/assets/fonts/open-sans/open-sans-v17-latin-regular.woff2
/usr/lib64/R/library/gfonts/assets/fonts/oswald/oswald-v40-latin-200.woff
/usr/lib64/R/library/gfonts/assets/fonts/oswald/oswald-v40-latin-200.woff2
/usr/lib64/R/library/gfonts/assets/fonts/oswald/oswald-v40-latin-700.woff
/usr/lib64/R/library/gfonts/assets/fonts/oswald/oswald-v40-latin-700.woff2
/usr/lib64/R/library/gfonts/assets/fonts/oswald/oswald-v40-latin-regular.woff
/usr/lib64/R/library/gfonts/assets/fonts/oswald/oswald-v40-latin-regular.woff2
/usr/lib64/R/library/gfonts/assets/fonts/poppins/poppins-v15-latin-300italic.woff
/usr/lib64/R/library/gfonts/assets/fonts/poppins/poppins-v15-latin-300italic.woff2
/usr/lib64/R/library/gfonts/assets/fonts/poppins/poppins-v15-latin-700.woff
/usr/lib64/R/library/gfonts/assets/fonts/poppins/poppins-v15-latin-700.woff2
/usr/lib64/R/library/gfonts/assets/fonts/poppins/poppins-v15-latin-regular.woff
/usr/lib64/R/library/gfonts/assets/fonts/poppins/poppins-v15-latin-regular.woff2
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-300italic.eot
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-300italic.svg
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-300italic.ttf
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-300italic.woff
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-300italic.woff2
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-700.eot
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-700.svg
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-700.ttf
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-700.woff
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-700.woff2
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-regular.eot
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-regular.svg
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-regular.ttf
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-regular.woff
/usr/lib64/R/library/gfonts/assets/fonts/roboto/roboto-v20-latin-regular.woff2
/usr/lib64/R/library/gfonts/assets/templates/css_best.txt
/usr/lib64/R/library/gfonts/assets/templates/css_modern.txt
/usr/lib64/R/library/gfonts/data/Rdata.rdb
/usr/lib64/R/library/gfonts/data/Rdata.rds
/usr/lib64/R/library/gfonts/data/Rdata.rdx
/usr/lib64/R/library/gfonts/doc/gfonts.R
/usr/lib64/R/library/gfonts/doc/gfonts.Rmd
/usr/lib64/R/library/gfonts/doc/gfonts.html
/usr/lib64/R/library/gfonts/doc/index.html
/usr/lib64/R/library/gfonts/help/AnIndex
/usr/lib64/R/library/gfonts/help/aliases.rds
/usr/lib64/R/library/gfonts/help/figures/included-fonts.png
/usr/lib64/R/library/gfonts/help/gfonts.rdb
/usr/lib64/R/library/gfonts/help/gfonts.rdx
/usr/lib64/R/library/gfonts/help/paths.rds
/usr/lib64/R/library/gfonts/html/00Index.html
/usr/lib64/R/library/gfonts/html/R.css
/usr/lib64/R/library/gfonts/testdata/fontsinfo.rds
/usr/lib64/R/library/gfonts/tests/testthat.R
/usr/lib64/R/library/gfonts/tests/testthat/generate_css.yml
/usr/lib64/R/library/gfonts/tests/testthat/get_all_fonts.yml
/usr/lib64/R/library/gfonts/tests/testthat/get_font_info_montserrat.yml
/usr/lib64/R/library/gfonts/tests/testthat/get_font_info_roboto.yml
/usr/lib64/R/library/gfonts/tests/testthat/helper-gfonts.R
/usr/lib64/R/library/gfonts/tests/testthat/test-api.R
/usr/lib64/R/library/gfonts/tests/testthat/test-css.R
/usr/lib64/R/library/gfonts/tests/testthat/test-setup_font.R
/usr/lib64/R/library/gfonts/tests/testthat/test-tag_example.R
/usr/lib64/R/library/gfonts/tests/testthat/test-use_font.R
/usr/lib64/R/library/gfonts/tests/testthat/test-use_pkg_gfont.R
